---
apiVersion: v1
kind: Service
metadata:
  name: izaac-test-redis-service
  labels:
    username: izaac
    env: test
spec:
  type: ClusterIP
  selector:
    app: izaac-test-redis
  ports:
  - name: redis-port
    port: 6379
    targetPort: 6379
