---
apiVersion: v1
kind: Service
metadata:
  name: izaac-test-flask-service
  labels:
    username: izaac
    env: test    
spec:
  type: ClusterIP
  selector:
    app: izaac-test-flask-app
  ports:
  - name: izaac-flask-port
    port: 5000
    targetPort: 5000
