---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: izaac-test-redis
  labels:
    app: izaac-test-redis
    username: izaac
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: izaac-test-redis
  template:
    metadata:
      labels:
        app: izaac-test-redis
        username: izaac
        env: test
    spec:
      containers:
        - name: redis
          image: redis:7
          volumeMounts:
          - name: pvc-storage
            mountPath: "/data"
      volumes:
      - name: pvc-storage
        persistentVolumeClaim:
          claimName: izaac-test-redis-pvc
